Testing plotting scripts before putting into the pipeline

In [1]:
%load_ext rpy2.ipython

In [2]:
%%R

library(ggplot2)
library(ggpubr)

In [5]:
import pandas as pd

## Read count plot

Bargraph seperated by flowcell

In [9]:
test_df = pd.read_csv('../notes/testFiles/PBEH1-1.00.barcodes.tsv', sep='\t', header=None)

In [11]:
cols = ['fwdBarcode', 'fwdBarcodeLoc', 'fwdRC', 'revBarcode', 'revBarcodeLoc', 'revRC', 'read', 'readLength']

In [12]:
test_df.columns = cols
test_df.head()

,fwdBarcode,fwdBarcodeLoc,fwdRC,revBarcode,revBarcodeLoc,revRC,read,readLength
0,TCTTTGGC,23,False,TCTTTGGC,2204,True,m64069_230413_005848/9/ccs,2374
1,TCTTTGGC,23,False,CGTTTCTG,2231,True,m64069_230413_005848/2623719/ccs,2403
2,CGTTTCTG,20,False,TATGGGGA,546,False,m64069_230413_005848/5373968/ccs/fwd,712
3,ATTGCTGG,134,False,CGGTTAGA,2224,True,m64069_230413_005848/8063037/ccs,2396
4,CGGTTAGA,21,False,TCTTTGGC,2248,True,m64069_230413_005848/10815127/ccs,2415

In [13]:
test_df['uniqueID'] = test_df.apply(lambda row: int(row.read.split('/')[1]), axis=1)

In [14]:
test_df

,fwdBarcode,fwdBarcodeLoc,fwdRC,revBarcode,revBarcodeLoc,revRC,read,readLength,uniqueID
0,TCTTTGGC,23,False,TCTTTGGC,2204,True,m64069_230413_005848/9/ccs,2374,9
1,TCTTTGGC,23,False,CGTTTCTG,2231,True,m64069_230413_005848/2623719/ccs,2403,2623719
2,CGTTTCTG,20,False,TATGGGGA,546,False,m64069_230413_005848/5373968/ccs/fwd,712,5373968
3,ATTGCTGG,134,False,CGGTTAGA,2224,True,m64069_230413_005848/8063037/ccs,2396,8063037
4,CGGTTAGA,21,False,TCTTTGGC,2248,True,m64069_230413_005848/10815127/ccs,2415,10815127
...,...,...,...,...,...,...,...,...,...
9995,CGGTTAGA,20,False,TCTTTGGC,2225,True,m64069_230413_005848/30279538/ccs/rev,2394,30279538
9996,CGGTTAGA,17,False,ATTGCTGG,2342,True,m64069_230413_005848/33096732/ccs,2402,33096732
9997,CGTTTCTG,20,False,TCTTTGGC,2226,True,m64069_230413_005848/35914315/ccs,2395,35914315
9998,CGTTTCTG,20,False,TCTTTGGC,2222,True,m64069_230413_005848/38669095/ccs/rev,2391,38669095
9999,ATGGATCG,20,False,CGTTTCTG,2205,True,m64069_230413_005848/41616183/ccs/rev,2382,41616183

Drop rows that are not unique reads

In [15]:
# chat GPT
def remove_duplicate_rows(df, key_col):
    """
    Identifies rows in a pandas dataframe that have a duplicate key value,
    and returns a new dataframe with only one row for each key value.

    Parameters:
    df (pandas.DataFrame): The dataframe to search for duplicates.
    key_col (str): The name of the column containing the key value.

    Returns:
    pandas.DataFrame: A dataframe containing only one row for each key value.
    """
    new_df = df.drop_duplicates(subset=key_col, keep='first')
    return new_df

In [18]:
test_df = remove_duplicate_rows(test_df, 'uniqueID')

Read sample df

In [46]:
test_df.loc[test_df['fwdBarcode'].isin(id_df['revBarcode'])]

,fwdBarcode,fwdBarcodeLoc,fwdRC,revBarcode,revBarcodeLoc,revRC,read,readLength,uniqueID
0,TCTTTGGC,23,False,TCTTTGGC,2204,True,m64069_230413_005848/9/ccs,2374,9
1,TCTTTGGC,23,False,CGTTTCTG,2231,True,m64069_230413_005848/2623719/ccs,2403,2623719
2,CGTTTCTG,20,False,TATGGGGA,546,False,m64069_230413_005848/5373968/ccs/fwd,712,5373968
3,ATTGCTGG,134,False,CGGTTAGA,2224,True,m64069_230413_005848/8063037/ccs,2396,8063037
4,CGGTTAGA,21,False,TCTTTGGC,2248,True,m64069_230413_005848/10815127/ccs,2415,10815127
...,...,...,...,...,...,...,...,...,...
9990,CGTTTCTG,20,False,TCTTTGGC,2231,True,m64069_230413_005848/16385222/ccs/fwd,2400,16385222
9992,CGTTTCTG,20,False,GGTAACAC,2228,True,m64069_230413_005848/21954788/ccs,2401,21954788
9994,ATTGCTGG,133,False,TCTTTGGC,2225,True,m64069_230413_005848/27525626/ccs,2394,27525626
9996,CGGTTAGA,17,False,ATTGCTGG,2342,True,m64069_230413_005848/33096732/ccs,2402,33096732
9997,CGTTTCTG,20,False,TCTTTGGC,2226,True,m64069_230413_005848/35914315/ccs,2395,35914315

In [21]:
id_df = pd.read_csv('../resources/PBEH-1-samples.tsv', sep='\t')

Merge based on fwd and rev barcodes

In [24]:
m1 = test_df.merge(id_df, on=['fwdBarcode', 'revBarcode'])

In [28]:
m1

,fwdBarcode,fwdBarcodeLoc,fwdRC,revBarcode,revBarcodeLoc,revRC,read,readLength,uniqueID,Sample-ID,...,Unnamed: 44,Unnamed: 45,SecondaryPCRForwardPrimer,SecondaryPCRReversePrimer,SecondaryPCRAgaroseGelExtractionDate,SecondartGelExtractionYeild,SecondaryPCRCycles,SecondaryPCRElutionVolume,SecondaryPCRDNAMassNg,TotalDNAMassAllPCRReactionsPooled
0,CGTTTCTG,20,False,CGGTTAGA,2224,True,m64069_230413_005848/75630078/ccs,2397,75630078,2,...,PacBioFwdV2-2,PacBioRevV2-0,paCBioFwdV2-,NaN,2-9-23,NaN,NaN,NaN,0.0,183.0
1,CGTTTCTG,20,False,CGGTTAGA,2223,True,m64069_230413_005848/52954103/ccs,2395,52954103,2,...,PacBioFwdV2-2,PacBioRevV2-0,paCBioFwdV2-,NaN,2-9-23,NaN,NaN,NaN,0.0,183.0
2,CGTTTCTG,19,False,CGGTTAGA,2223,True,m64069_230413_005848/163776986/ccs,2395,163776986,2,...,PacBioFwdV2-2,PacBioRevV2-0,paCBioFwdV2-,NaN,2-9-23,NaN,NaN,NaN,0.0,183.0
3,CGTTTCTG,18,False,CGGTTAGA,2221,True,m64069_230413_005848/38731845/ccs/fwd,2393,38731845,2,...,PacBioFwdV2-2,PacBioRevV2-0,paCBioFwdV2-,NaN,2-9-23,NaN,NaN,NaN,0.0,183.0
4,CGTTTCTG,19,False,CGGTTAGA,2262,True,m64069_230413_005848/44499276/ccs,2395,44499276,2,...,PacBioFwdV2-2,PacBioRevV2-0,paCBioFwdV2-,NaN,2-9-23,NaN,NaN,NaN,0.0,183.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1046,ATGGATCG,20,False,CGGTTAGA,2223,True,m64069_230413_005848/143984975/ccs,2395,143984975,5,...,PacBioFwdV2-3,PacBioRevV2-0,NaN,NaN,0,NaN,NaN,NaN,0.0,2037.0
1047,ATGGATCG,20,False,CGGTTAGA,2214,True,m64069_230413_005848/169478635/ccs/fwd,2386,169478635,5,...,PacBioFwdV2-3,PacBioRevV2-0,NaN,NaN,0,NaN,NaN,NaN,0.0,2037.0
1048,GGTAACAC,20,False,ACGGAACA,1351,True,m64069_230413_005848/522/ccs,1528,522,38,...,PacBioFwdV2-4,PacBioRevV2-25-P9,NaN,NaN,0,NaN,NaN,NaN,0.0,1086.0
1049,GGTAACAC,17,False,CACCTATG,2137,False,m64069_230413_005848/52954001/ccs/fwd,2222,52954001,17,...,PacBioFwdV2-4,PacBioRevV2-24-P9,NaN,NaN,0,NaN,NaN,NaN,0.0,775.0
1050,ACCTCAGT,185,True,TATGGGGA,2223,True,m64069_230413_005848/81331153/ccs,2229,81331153,48,...,PacBioFwdV2-6,PacBioRevV2-17-AplI,NaN,NaN,0,NaN,NaN,NaN,0.0,2016.0

Damn thats not a lot of reads what barcodes are things mapping to?

In [37]:
fwdbar_df = id_df[['fwdBarcode', 'FWDPrimer']]
revbar_df = id_df[['revBarcode', 'REVPrimer']]

In [40]:
test_bar = test_df.merge(fwdbar_df, on='fwdBarcode')
test_bar = test_bar.merge(revbar_df, on='revBarcode')

remove_duplicate_rows(test_bar, 'uniqueID')

,fwdBarcode,fwdBarcodeLoc,fwdRC,revBarcode,revBarcodeLoc,revRC,read,readLength,uniqueID,FWDPrimer,REVPrimer
0,CGTTTCTG,20,False,TATGGGGA,546,False,m64069_230413_005848/5373968/ccs/fwd,712,5373968,PacBioFwdV2-2,PacBioRevV2-17-AplI
28,CGTTTCTG,19,False,TATGGGGA,1399,True,m64069_230413_005848/123996405/ccs,1579,123996405,PacBioFwdV2-2,PacBioRevV2-17-AplI
56,CGTTTCTG,20,False,TATGGGGA,2343,True,m64069_230413_005848/69929535/ccs,2463,69929535,PacBioFwdV2-2,PacBioRevV2-17-AplI
84,CGTTTCTG,20,False,TATGGGGA,1784,True,m64069_230413_005848/177865550/ccs,1848,177865550,PacBioFwdV2-2,PacBioRevV2-17-AplI
112,CGTTTCTG,20,False,TATGGGGA,2270,True,m64069_230413_005848/126877933/ccs,2391,126877933,PacBioFwdV2-2,PacBioRevV2-17-AplI
...,...,...,...,...,...,...,...,...,...,...,...
76389,CGGTTAGA,20,False,TACGCAAG,292,False,m64069_230413_005848/166595197/ccs,384,166595197,PacBioFwdV2-0,PacBioRevV2-18-AplI
76425,CGGTTAGA,21,False,TACGCAAG,2367,False,m64069_230413_005848/143985078/ccs,2392,143985078,PacBioFwdV2-0,PacBioRevV2-18-AplI
76461,CGGTTAGA,20,False,TACGCAAG,1272,True,m64069_230413_005848/41616265/ccs,1299,41616265,PacBioFwdV2-0,PacBioRevV2-18-AplI
76497,GGTAACAC,20,False,TACGCAAG,2361,False,m64069_230413_005848/16385031/ccs,2386,16385031,PacBioFwdV2-4,PacBioRevV2-18-AplI
76525,CCCTCTTT,20,False,TACGCAAG,2366,False,m64069_230413_005848/55772680/ccs,2391,55772680,PacBioFwdV2-1,PacBioRevV2-18-AplI

Get rows that have fwd barcodes identified as the reverse barcode

Read in plasmid identification info and merge that in as well, that data will be under read_name

In [26]:
plas_df = pd.read_csv('/home/ethollem/workflows/PBEH1/workflow/output/blast/plasmidID/PBEH1-1/00/plasmidID.tsv', sep='\t')

In [27]:
m1.merge(plas_df, left_on='read', right_on='read_name')

,fwdBarcode,fwdBarcodeLoc,fwdRC,revBarcode,revBarcodeLoc,revRC,read,readLength,uniqueID,Sample-ID,...,SecondaryPCRForwardPrimer,SecondaryPCRReversePrimer,SecondaryPCRAgaroseGelExtractionDate,SecondartGelExtractionYeild,SecondaryPCRCycles,SecondaryPCRElutionVolume,SecondaryPCRDNAMassNg,TotalDNAMassAllPCRReactionsPooled,ref_name,read_name
0,CGTTTCTG,20,False,CGGTTAGA,2224,True,m64069_230413_005848/75630078/ccs,2397,75630078,2,...,paCBioFwdV2-,NaN,2-9-23,NaN,NaN,NaN,0.0,183.0,T7_init_VR-23.gb,m64069_230413_005848/75630078/ccs
1,CGTTTCTG,20,False,CGGTTAGA,2223,True,m64069_230413_005848/52954103/ccs,2395,52954103,2,...,paCBioFwdV2-,NaN,2-9-23,NaN,NaN,NaN,0.0,183.0,T7_init_VR-23.gb,m64069_230413_005848/52954103/ccs
2,CGTTTCTG,19,False,CGGTTAGA,2223,True,m64069_230413_005848/163776986/ccs,2395,163776986,2,...,paCBioFwdV2-,NaN,2-9-23,NaN,NaN,NaN,0.0,183.0,T7_init_VR-29.gb,m64069_230413_005848/163776986/ccs
3,CGTTTCTG,18,False,CGGTTAGA,2221,True,m64069_230413_005848/38731845/ccs/fwd,2393,38731845,2,...,paCBioFwdV2-,NaN,2-9-23,NaN,NaN,NaN,0.0,183.0,T7_init_VR-12.gb,m64069_230413_005848/38731845/ccs/fwd
4,CGTTTCTG,19,False,CGGTTAGA,2262,True,m64069_230413_005848/44499276/ccs,2395,44499276,2,...,paCBioFwdV2-,NaN,2-9-23,NaN,NaN,NaN,0.0,183.0,T7_init_VR-14.gb,m64069_230413_005848/44499276/ccs
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
953,ATGGATCG,20,False,CGGTTAGA,2227,True,m64069_230413_005848/75630472/ccs/fwd,2399,75630472,5,...,NaN,NaN,0,NaN,NaN,NaN,0.0,2037.0,T7_init_VR-29.gb,m64069_230413_005848/75630472/ccs/fwd
954,ATGGATCG,20,False,CGGTTAGA,2223,True,m64069_230413_005848/143984975/ccs,2395,143984975,5,...,NaN,NaN,0,NaN,NaN,NaN,0.0,2037.0,T7_init_VR-7.gb,m64069_230413_005848/143984975/ccs
955,ATGGATCG,20,False,CGGTTAGA,2214,True,m64069_230413_005848/169478635/ccs/fwd,2386,169478635,5,...,NaN,NaN,0,NaN,NaN,NaN,0.0,2037.0,T7_init_VR-18.gb,m64069_230413_005848/169478635/ccs/fwd
956,GGTAACAC,17,False,CACCTATG,2137,False,m64069_230413_005848/52954001/ccs/fwd,2222,52954001,17,...,NaN,NaN,0,NaN,NaN,NaN,0.0,775.0,T7_init_VR-6.gb,m64069_230413_005848/52954001/ccs/fwd
957,ACCTCAGT,185,True,TATGGGGA,2223,True,m64069_230413_005848/81331153/ccs,2229,81331153,48,...,NaN,NaN,0,NaN,NaN,NaN,0.0,2016.0,T7_init_VR-14.gb,m64069_230413_005848/81331153/ccs